import { ConversionResult } from "./converter";
import { nbt, writeNbt, gzip, NbtTag } from "./nbt";

// Minecraft 1.20.1 data version — widely compatible with current WorldEdit & Litematica.
const DATA_VERSION = 3465;

export type Orientation = "wall" | "floor";

/**
 * Lays the pixel art into a 3D block grid for export.
 *   - "wall":  upright — X = column, Y = row (flipped so image top is up), Z = 1 thick.
 *   - "floor": flat on the ground for map art — X = column, Z = row, Y = 1 thick.
 * Index ordering follows the schematic convention: x + z*dimX + y*dimX*dimZ.
 */
function buildGrid(result: ConversionResult, orientation: Orientation = "wall") {
  const { pixels, width, height } = result;
  const paletteIndex = new Map<string, number>();
  const paletteIds: string[] = [];

  const dimX = width;
  const dimY = orientation === "wall" ? height : 1;
  const dimZ = orientation === "wall" ? 1 : height;
  const indices = new Array<number>(dimX * dimY * dimZ);

  for (let row = 0; row < height; row++) {
    for (let x = 0; x < width; x++) {
      const id = pixels[row][x].block.id;
      let idx = paletteIndex.get(id);
      if (idx === undefined) {
        idx = paletteIds.length;
        paletteIndex.set(id, idx);
        paletteIds.push(id);
      }
      const X = x;
      const Y = orientation === "wall" ? height - 1 - row : 0;
      const Z = orientation === "wall" ? 0 : row;
      indices[X + Z * dimX + Y * dimX * dimZ] = idx;
    }
  }

  return { dimX, dimY, dimZ, paletteIds, indices };
}

function triggerDownload(bytes: Uint8Array, filename: string) {
  const blob = new Blob([bytes as unknown as BlobPart], { type: "application/octet-stream" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/* ─────────────── .mcfunction (datapack / command) ─────────────── */

export function downloadMcfunction(result: ConversionResult, name = "pixel-art", orientation: Orientation = "wall") {
  const { pixels, height } = result;
  const lines: string[] = [
    `# ${name} — generated by mcimagetool.com`,
    orientation === "wall"
      ? `# Run with the build origin at ~ ~ ~ (facing the wall).`
      : `# Flat map art — run with the origin at the north-west corner.`,
  ];
  for (let row = 0; row < height; row++) {
    for (const cell of pixels[row]) {
      const X = cell.x;
      const Y = orientation === "wall" ? height - 1 - row : 0;
      const Z = orientation === "wall" ? 0 : row;
      lines.push(`setblock ~${X} ~${Y} ~${Z} minecraft:${cell.block.id}`);
    }
  }
  const bytes = new TextEncoder().encode(lines.join("\n"));
  triggerDownload(bytes, `${name}.mcfunction`);
}

/* ─────────────── Sponge .schem (WorldEdit) ─────────────── */

function writeVarInt(out: number[], value: number) {
  let v = value >>> 0;
  while (true) {
    if ((v & ~0x7f) === 0) { out.push(v); return; }
    out.push((v & 0x7f) | 0x80);
    v >>>= 7;
  }
}

export async function downloadSchem(result: ConversionResult, name = "pixel-art", orientation: Orientation = "wall") {
  const { dimX, dimY, dimZ, paletteIds, indices } = buildGrid(result, orientation);

  const paletteTag: Record<string, NbtTag> = {};
  paletteIds.forEach((id, i) => {
    paletteTag[`minecraft:${id}`] = nbt.int(i);
  });

  const blockData: number[] = [];
  for (const idx of indices) writeVarInt(blockData, idx);

  const root = nbt.compound({
    Version: nbt.int(2),
    DataVersion: nbt.int(DATA_VERSION),
    Width: nbt.short(dimX),
    Height: nbt.short(dimY),
    Length: nbt.short(dimZ),
    PaletteMax: nbt.int(paletteIds.length),
    Palette: nbt.compound(paletteTag),
    BlockData: nbt.byteArray(Uint8Array.from(blockData)),
    Offset: nbt.intArray([0, 0, 0]),
    Metadata: nbt.compound({
      Name: nbt.string(name),
      Author: nbt.string("Minecraft Pixel Art Generator"),
    }),
  });

  const bytes = await gzip(writeNbt("Schematic", root));
  triggerDownload(bytes, `${name}.schem`);
}

/* ─────────────── Litematica .litematic ─────────────── */

function packBitArray(indices: number[], bits: number): bigint[] {
  const mask = (1n << BigInt(bits)) - 1n;
  const max64 = (1n << 64n) - 1n;
  const longCount = Math.ceil((indices.length * bits) / 64);
  const longs = new Array<bigint>(longCount).fill(0n);

  for (let i = 0; i < indices.length; i++) {
    const val = BigInt(indices[i]) & mask;
    const bitIndex = i * bits;
    const startLong = Math.floor(bitIndex / 64);
    const startOffset = bitIndex % 64;
    const endLong = Math.floor((bitIndex + bits - 1) / 64);

    longs[startLong] = (longs[startLong] | (val << BigInt(startOffset))) & max64;
    if (startLong !== endLong) {
      longs[endLong] = (longs[endLong] | (val >> BigInt(64 - startOffset))) & max64;
    }
  }
  return longs;
}

export async function downloadLitematic(result: ConversionResult, name = "pixel-art", orientation: Orientation = "wall") {
  const { dimX, dimY, dimZ, paletteIds, indices } = buildGrid(result, orientation);

  // Litematica needs air at palette index 0; rebuild palette + indices with the shift.
  const palette = ["air", ...paletteIds];
  const shifted = indices.map((i) => i + 1);

  const bits = Math.max(2, Math.ceil(Math.log2(palette.length)));
  const longs = packBitArray(shifted, bits);

  const paletteList = palette.map((id) =>
    nbt.compound({ Name: nbt.string(`minecraft:${id}`) })
  );

  const total = dimX * dimY * dimZ;
  const now = BigInt(Date.now());

  const region = nbt.compound({
    Position: nbt.compound({ x: nbt.int(0), y: nbt.int(0), z: nbt.int(0) }),
    Size: nbt.compound({ x: nbt.int(dimX), y: nbt.int(dimY), z: nbt.int(dimZ) }),
    BlockStatePalette: nbt.list(nbt.typeId("compound"), paletteList),
    BlockStates: nbt.longArray(longs),
    TileEntities: nbt.list(nbt.typeId("compound"), []),
    Entities: nbt.list(nbt.typeId("compound"), []),
    PendingBlockTicks: nbt.list(nbt.typeId("compound"), []),
    PendingFluidTicks: nbt.list(nbt.typeId("compound"), []),
  });

  const root = nbt.compound({
    MinecraftDataVersion: nbt.int(DATA_VERSION),
    Version: nbt.int(6),
    Metadata: nbt.compound({
      Name: nbt.string(name),
      Author: nbt.string("Minecraft Pixel Art Generator"),
      Description: nbt.string("Generated pixel art"),
      EnclosingSize: nbt.compound({ x: nbt.int(dimX), y: nbt.int(dimY), z: nbt.int(dimZ) }),
      TimeCreated: nbt.long(now),
      TimeModified: nbt.long(now),
      TotalBlocks: nbt.int(total),
      TotalVolume: nbt.int(total),
      RegionCount: nbt.int(1),
    }),
    Regions: nbt.compound({ [name]: region }),
  });

  const bytes = await gzip(writeNbt("", root));
  triggerDownload(bytes, `${name}.litematic`);
}
